### ISSUE TITLE
changeAddress question

### ISSUE THREAD

**Issue by MungoBerry** [duff2013/SDI12_T3#3]
Hi,

it is possible to get data from two sensors using changeAddress ?
(declaring only one sensor)
I use the following code without success:

> #include "SDI12.h"
> 
> #define sdi12_PIN		6
> #define MAX_DATA		75
> #define INVALID_VALUE	-9999
> 
> #define SENSORS_COUNT	2
> 
> SDI12 sensor(&Serial3, '0');
> 
> void setup()
> {
> 	pinMode(sdi12_PIN, OUTPUT);
> 	digitalWrite(sdi12_PIN, LOW);
> 	
> 	delay(5000);
> }
> 
> void loop()
> {
> 	char data[MAX_DATA+1];
> 	char debug[10];
> 	float wm;
> 	float tmp;
> 	
> 	for ( char address = '0'; address < SENSORS_COUNT; ++address )
> 	{
> 		sensor.changeAddress(address);
> 		
> 		memset(data, 0, MAX_DATA+1);
> 			
> 		if ( ! sensor.measurement(debug) )
> 			sensor.returnMeasurement(data, 0);
> 		
> 		if ( (strlen(data) < 3) || (sscanf(data+3, "%f+%f", &wm, &tmp) != 2 ) )
> 		{
> 			wm = INVALID_VALUE;
> 			tmp = INVALID_VALUE;
> 		}
> 		
> 		Serial.printf("sensor at %c: wm: %f, tmp: %f\n", address, wm, tmp);	
> 	}
> 	
> 	delay(5000);
> }
>

**Comment by duff2013** [comment]
changeAddress does just that, change the address of the sensor. I believe it only returns the new address and you should only do that once with not other sensor connected to the bus.

**Comment by MungoBerry** [comment]
Thank you.
